tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      ./aws/install --install-dir /workspace/aws-cli --bin-dir /workspace/bin
      export PATH=/workspace/bin:$PATH
      cd /workspace/aws-course
