#!/usr/bin/env bash
echo "== Delete bucket"

if [ -z "$1" ]; then
    echo "No bucket name Provided"
    exit 1
fi
BUCKET_NAME=$1
echo "Bucket name is $BUCKET_NAME"

aws s3api delete-bucket --bucket $BUCKET_NAME